name: Kawi
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69505086-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#6b6360'
    - '#fc8d25'
    - '#e0e0e0'
    - '#21d261'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
